#!/usr/bin/env bash
set -e

FILE="/orderly2outpack/orderly2outpack"

Rscript /orderly2outpack/schedule.R "$@"

# if the file has been created, start yacron
if test -f "$FILE"; then
    chmod +x $FILE
    echo "*** Starting scheduler ***"
    cat /orderly2outpack/schedule.yml
    yacron -c /orderly2outpack/schedule.yml
fi
