#!/usr/bin/env bash
set -e

usermod -u "$USER_ID" outpack

FILE="/home/outpack/outpack.hourly"
sudo -u outpack Rscript /orderly2outpack/orderly2outpack.R "$@"

if test -f "$FILE"; then
    chmod +x $FILE
    echo "@hourly Rscript /home/outpack/outpack.hourly >> /var/log/outpack.log 2>&1" >> tab.txt
    crontab -u outpack tab.txt
    cron -f
fi
