web:
  listen:
    - http://0.0.0.0:1234
    - unix:///tmp/yacron.sock
jobs:
  - name: orderly2outpack-cron
    failsWhen:
      producesStderr: false
      producesStdout: false
      nonzeroReturn: true
      always: false
