#!/usr/bin/env bash

set -e
HERE=$(dirname $0)
. $HERE/common

SRC=/tmp/src
DEST=/tmp/dest
ORDERLY_IMAGE=vimc/orderly:master

mkdir $DEST -p
mkdir $SRC -p

function cleanup() {
   rm $SRC -rf
   rm $DEST -rf
   docker rm orderly2outpack -f
}

trap cleanup EXIT

docker pull $ORDERLY_IMAGE
docker run --rm \
    --entrypoint 'create_orderly_demo.sh' \
    -u $UID \
    -v $SRC:/orderly \
    -w "/orderly" \
    $ORDERLY_IMAGE \
    "."

docker pull $TAG_SHA
docker run -v $SRC:/orderly:ro \
           -v $DEST:/outpack \
           --name orderly2outpack \
           --env USER_ID=$UID \
           -d \
           $TAG_SHA /orderly/demo /outpack --custom="* * * * *"

# this is annoying but can't figure out another way around this
sleep 60

docker logs orderly2outpack

if test -f "$DEST/.outpack/config.json"; then
  exit 0
else
  exit 1
fi
